manifest:
  remotes:
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
    - name: rianadon
      url-base: https://github.com/rianadon
    - name: pedantic
      url-base: https://github.com/pedanticavenger
  projects:
    - name: zmk-fingerpunch-vik
      remote: rianadon
      revision: main
      import: config/deps.yml
